# Generated by Django 6.0.6 on 2026-07-05 19:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrappedEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.CharField(max_length=998)),
                ('from_email', models.CharField(blank=True, default='', max_length=998)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('body_html', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(blank=True, default='')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('scope_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scope_key', 'created_at'], name='mailtrap_scope_created')],
            },
        ),
    ]
